/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego.piedra.papel.y.tijera;

/**
 *
 * @author familia
 */
public class interfacejuego extends javax.swing.JPanel {

    /**
     * Creates new form interfacejuego
     */
    public interfacejuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Piedra = new javax.swing.JButton();
        Papel = new javax.swing.JButton();
        Tijera = new javax.swing.JButton();
        Piedra1 = new javax.swing.JButton();
        Papel1 = new javax.swing.JButton();
        Tijera1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Piedra.setText("Piedra");
        Piedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiedraActionPerformed(evt);
            }
        });
        add(Piedra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        Papel.setText("Papel");
        add(Papel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, -1));

        Tijera.setText("Tijera");
        Tijera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TijeraActionPerformed(evt);
            }
        });
        add(Tijera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 80, -1));

        Piedra1.setText("Piedra");
        Piedra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Piedra1ActionPerformed(evt);
            }
        });
        add(Piedra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        Papel1.setText("Papel");
        add(Papel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 80, -1));

        Tijera1.setText("Tijera");
        Tijera1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tijera1ActionPerformed(evt);
            }
        });
        add(Tijera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vs.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void PiedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiedraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PiedraActionPerformed

    private void TijeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TijeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TijeraActionPerformed

    private void Piedra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Piedra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Piedra1ActionPerformed

    private void Tijera1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tijera1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tijera1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Papel;
    private javax.swing.JButton Papel1;
    private javax.swing.JButton Piedra;
    private javax.swing.JButton Piedra1;
    private javax.swing.JButton Tijera;
    private javax.swing.JButton Tijera1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
